"""add missing device columns

Revision ID: 9a10b793949b
Revises: 093c40141913
Create Date: 2026-07-22 16:07:02.952236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a10b793949b'
down_revision: Union[str, Sequence[str], None] = '093c40141913'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_heartbeats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('cpu_usage', sa.Float(), nullable=False),
    sa.Column('memory_usage', sa.Float(), nullable=False),
    sa.Column('disk_usage', sa.Float(), nullable=False),
    sa.Column('battery_level', sa.Integer(), nullable=False),
    sa.Column('logged_in_user', sa.String(length=100), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=False),
    sa.Column('network_name', sa.String(length=100), nullable=True),
    sa.Column('uptime_seconds', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_heartbeats_id'), 'device_heartbeats', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_device_heartbeats_id'), table_name='device_heartbeats')
    op.drop_table('device_heartbeats')
    # ### end Alembic commands ###
