"""add_device_uuid_to_devices

Revision ID: ddd11860e6c4
Revises: b2d3f4a5c6e7
Create Date: 2026-07-22 13:37:34.700427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddd11860e6c4'
down_revision: Union[str, Sequence[str], None] = 'b2d3f4a5c6e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('device_uuid', sa.String(length=100), nullable=True))
    op.create_unique_constraint(None, 'devices', ['device_uuid'])
    op.add_column('devices', sa.Column('manufacturer', sa.String(length=100), nullable=True))
    op.add_column('devices', sa.Column('model', sa.String(length=100), nullable=True))
    op.add_column('devices', sa.Column('platform', sa.String(length=100), nullable=True))
    op.add_column('devices', sa.Column('os_name', sa.String(length=100), nullable=True))
    op.add_column('devices', sa.Column('os_version', sa.String(length=100), nullable=True))
    op.add_column('devices', sa.Column('processor', sa.String(length=100), nullable=True))
    op.add_column('devices', sa.Column('memory_gb', sa.Float(), nullable=True))
    op.add_column('devices', sa.Column('storage_gb', sa.Float(), nullable=True))
    op.add_column('devices', sa.Column('status', sa.String(length=50), nullable=True))
    op.add_column('devices', sa.Column('device_token_hash', sa.String(length=255), nullable=True))
    op.add_column('devices', sa.Column('token_created_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('devices', sa.Column('token_last_used', sa.DateTime(timezone=True), nullable=True))
    op.add_column('devices', sa.Column('registration_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('devices', sa.Column('registered_by', sa.String(length=100), nullable=True))
    op.add_column('devices', sa.Column('is_registered', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'is_registered')
    op.drop_column('devices', 'registered_by')
    op.drop_column('devices', 'registration_date')
    op.drop_column('devices', 'token_last_used')
    op.drop_column('devices', 'token_created_at')
    op.drop_column('devices', 'device_token_hash')
    op.drop_column('devices', 'status')
    op.drop_column('devices', 'storage_gb')
    op.drop_column('devices', 'memory_gb')
    op.drop_column('devices', 'processor')
    op.drop_column('devices', 'os_version')
    op.drop_column('devices', 'os_name')
    op.drop_column('devices', 'platform')
    op.drop_column('devices', 'model')
    op.drop_column('devices', 'manufacturer')
    op.drop_constraint(None, 'devices', type_='unique')
    op.drop_column('devices', 'device_uuid')
    # ### end Alembic commands ###
