from sqlalchemy import Column, DateTime, Float, ForeignKey, Integer, String
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func

from app.core.database import Base


class DeviceHeartbeat(Base):
    __tablename__ = "device_heartbeats"

    id = Column(Integer, primary_key=True, index=True)
    device_id = Column(Integer, ForeignKey("devices.id"), nullable=False)
    cpu_usage = Column(Float, nullable=False)
    memory_usage = Column(Float, nullable=False)
    disk_usage = Column(Float, nullable=False)
    battery_level = Column(Integer, nullable=False)
    logged_in_user = Column(String(100), nullable=True)
    ip_address = Column(String(50), nullable=False)
    network_name = Column(String(100), nullable=True)
    # Primary physical network interface's hardware MAC address
    # ("XX:XX:XX:XX:XX:XX"), reported by the agent -- never computed or
    # inferred server-side. NULL until the agent reports one.
    mac_address = Column(String(17), nullable=True)
    uptime_seconds = Column(Integer, nullable=False)
    timestamp = Column(DateTime(timezone=True), nullable=False, server_default=func.now())

    # Heartbeat ID generated by the endpoint/client SQLite database,
    # mirroring the sessions.local_session_id / applications.local_application_id
    # / idle_events.local_idle_id pattern (Phase 3, Item 5). No
    # uniqueness is enforced yet -- the currently deployed 7.7.9 agent
    # never sends this field, so it is present but functionally inert
    # until a future client actually populates it.
    local_heartbeat_id = Column(Integer, nullable=True)

    device = relationship("Device", backref="heartbeats")
