from sqlalchemy import Column, Integer, DateTime, ForeignKey, UniqueConstraint
from sqlalchemy.sql import func
from sqlalchemy.orm import relationship

from app.core.database import Base


class IdleEvent(Base):
    __tablename__ = "idle_events"

    id = Column(Integer, primary_key=True, index=True)

    device_id = Column(
        Integer,
        ForeignKey("devices.id"),
        nullable=False,
    )

    session_id = Column(
        Integer,
        ForeignKey("sessions.id"),
        nullable=False,
    )

    idle_start = Column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
    )

    idle_end = Column(
        DateTime(timezone=True),
        nullable=True,
    )

    idle_seconds = Column(
        Integer,
        nullable=True,
    )

    # Idle-event ID generated by the endpoint/client SQLite database.
    # The same local idle ID may exist on different devices, therefore
    # uniqueness is enforced together with device_id -- mirroring the
    # existing sessions.local_session_id / applications.local_application_id
    # pattern (Phase 3, Item 5: this constraint was previously missing
    # here despite the column existing; verified read-only against
    # production data before adding it that zero rows have a NULL
    # local_idle_id and zero duplicate (device_id, local_idle_id) pairs
    # exist).
    local_idle_id = Column(
        Integer,
        nullable=True,
    )

    device = relationship("Device")
    session = relationship("Session")

    __table_args__ = (
        UniqueConstraint(
            "device_id",
            "local_idle_id",
            name="uq_idle_events_device_local_idle",
        ),
    )
