from sqlalchemy import (
    Column,
    Integer,
    String,
    DateTime,
    ForeignKey,
    UniqueConstraint,
)
from sqlalchemy.sql import func
from sqlalchemy.orm import relationship

from app.core.database import Base


class Session(Base):
    __tablename__ = "sessions"

    id = Column(
        Integer,
        primary_key=True,
        index=True,
    )

    device_id = Column(
        Integer,
        ForeignKey("devices.id"),
        nullable=False,
        index=True,
    )

    # Session ID generated by the endpoint/client SQLite database.
    # The same local session ID may exist on different devices,
    # therefore uniqueness is enforced together with device_id.
    local_session_id = Column(
        Integer,
        nullable=True,
    )

    username = Column(
        String(100),
        nullable=False,
    )

    login_time = Column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
    )

    logout_time = Column(
        DateTime(timezone=True),
        nullable=True,
    )

    status = Column(
        String(20),
        nullable=False,
        default="ACTIVE",
    )

    device = relationship("Device")

    __table_args__ = (
        UniqueConstraint(
            "device_id",
            "local_session_id",
            name="uq_sessions_device_local_session",
        ),
    )
